#include<iostream.h>
#include<conio.h>

 main()
{ int bil1,bil2;

cout<<"masukan bilangan pertama  : ";
cin>>bil1;
cout<<"masukan bilangan kedua : ";
 cin>>bil2;
cout<<"hasil "<<bil1<<" + "<<bil2<<" = "<<(bil1+bil2);
cout<<"hasil "<<bil1<<" - "<<bil2<<" = "<<(bil1-bil2);
cout<<"hasil "<<bil1<<" * "<<bil2<<" = "<<(bil1*bil2);
cout<<"hasil "<<bil1<<" / "<<bil2<<" = "<<(bil1/bil2);
cout<<"hasil "<<bil1<<" % "<<bil2<<" = "<<(bil1%bil2);
return (0);
getch();
}
